---
mybatis:
  config-location: classpath:conf/mybatis-config.xml
  mapper-locations: classpath:sqlmap/*.xml


logging:
  level:
    org.springframework.web: info
    com.echo.backend: debug
  file:
    name: logs/all.log

spring:
  datasource:
    url: jdbc:mysql://18.162.53.247:3306/onpro
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root9900