server:
  servlet:
    context-path: /api
---
mybatis:
  config-location: classpath:conf/mybatis-config.xml
  mapper-locations: classpath:sqlmap/*.xml


logging:
  level:
    org.springframework.web: info
    com.echo.backend: debug
    com.echo.backend.dao: debug
  file:
    name: ../logs/run.out

spring:
  jackson:
    time-zone: GMT+11
  datasource:
    url: jdbc:mysql://18.166.66.215:3306/onpro?characterEncoding=utf8&serverTimezone=Australia/Sydney
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root9900
    hikari:
      max-lifetime: 500000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.live.com
    port: 587
    username: online_property9900@hotmail.com
    password: property9900
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false



server:
  file:
    upload:
      path: /Users/yang/Documents/apache-tomcat-9.0.39/webapps/resources #/home/ubuntu/tomcat/apache-tomcat/webapps/resources
    access:
      path: /resources/property/