server:
  servlet:
    context-path: /api
---
mybatis:
  config-location: classpath:conf/mybatis-config.xml
  mapper-locations: classpath:sqlmap/*.xml


logging:
  level:
    org.springframework.web: info
    com.echo.backend: debug
    com.echo.backend.dao: debug
  file:
    name: ../logs/run.out

spring:
  jackson:
    time-zone: GMT+11
  datasource:
    url: jdbc:mysql://18.166.66.215:3306/onpro?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root9900
    hikari:
      max-lifetime: 500000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  file:
    upload:
      path: /home/ubuntu/tomcat/apache-tomcat/webapps/resources
    access:
      path: /resources/property/
